#Application URl
url = https://automationexercise.com/login

#Browser Configuration
browser = chrome
#Credentials
userid= deepa@gmail.com
password= 18speed02

#ImplicitWait (in seconds)
implicitwait= 10

#Explicit wait
explicitwait = 10



